// Generated by gencpp from file gps_imu_driver/convert_to_quaternionRequest.msg
// DO NOT EDIT!


#ifndef GPS_IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNIONREQUEST_H
#define GPS_IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps_imu_driver
{
template <class ContainerAllocator>
struct convert_to_quaternionRequest_
{
  typedef convert_to_quaternionRequest_<ContainerAllocator> Type;

  convert_to_quaternionRequest_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  convert_to_quaternionRequest_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct convert_to_quaternionRequest_

typedef ::gps_imu_driver::convert_to_quaternionRequest_<std::allocator<void> > convert_to_quaternionRequest;

typedef boost::shared_ptr< ::gps_imu_driver::convert_to_quaternionRequest > convert_to_quaternionRequestPtr;
typedef boost::shared_ptr< ::gps_imu_driver::convert_to_quaternionRequest const> convert_to_quaternionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator1> & lhs, const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator1> & lhs, const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps_imu_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeec8b25a660789a89540dedcb2b06d6";
  }

  static const char* value(const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeec8b25a660789aULL;
  static const uint64_t static_value2 = 0x89540dedcb2b06d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_imu_driver/convert_to_quaternionRequest";
  }

  static const char* value(const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct convert_to_quaternionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_imu_driver::convert_to_quaternionRequest_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNIONREQUEST_H
